### ISSUE TITLE
Old Theme

### ISSUE THREAD

**Issue by duncdrum** [exc-asia-and-europe/wsc#8]
The link on the HRA homepage shows the following WSC homepage.
![screenshot 2015-03-04 10 24 13](https://cloud.githubusercontent.com/assets/6205362/6480950/5bc51a0e-c259-11e4-981e-545a12a65c1c.png)
This is how it currently looks:
![screenshot 2015-03-04 10 24 45](https://cloud.githubusercontent.com/assets/6205362/6480951/652eeb10-c259-11e4-8140-6974a0611da9.png)

The background images are still in the repo. @kajawang any idea whats going on here, and do we want the old theme back or not?

**Comment by claudius108** [comment]
Hi,

Can we move these discussions on redmine, and let github for third parties' suggestions?

Claudius

**Comment by duncdrum** [comment]
Done, not sure about who 3rd parties might be though :)
